### ISSUE TITLE
does remark-lint require git

### ISSUE THREAD

**Issue by wesley-dean-flexion** [zemanlx/remark-lint#8]
Hi.  I'm trying to see what I'm doing wrong here..

I'm attempting to lint a one-off markdown file that's in a directory not managed by git.  The tool finds warnings as one would expect, but it also issues an error asserting that the directory is not a part of a git repository after a failed `git remote -v` request.  

So, question is, does remark-lint require that the directory being scanned belong to a git repository?

```sh
$ ls 
untitled.md

$ docker run --rm -i -v $PWD:/lint/input:ro zemanlx/remark-lint .
untitled.md
     1:1  error    Error: Command failed: git remote -v
fatal: not a git repository (or any parent up to mount point /lint)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
   34:83  warning  Line must be at most 80 characters    maximum-line-length  remark-lint
   37:83  warning  Line must be at most 80 characters    maximum-line-length  remark-lint
   70:94  warning  Line must be at most 80 characters    maximum-line-length  remark-lint
   81:92  warning  Line must be at most 80 characters    maximum-line-length  remark-lint
  112:85  warning  Line must be at most 80 characters    maximum-line-length  remark-lint
  205:83  warning  Line must be at most 80 characters    maximum-line-length  remark-lint

7 messages (✖ 1 error, ⚠ 6 warnings)
```

**Comment by zemanlx** [comment]
To be honest, I have no idea. I have never used it outside of git repo. JS is my least preferred language and I am using Docker, in this case, to make it a bit more bearable. However, to make it work in Docker it requires [git](https://github.com/zemanlx/remark-lint/blob/master/Dockerfile#L7) as a dependency.

**Comment by achatain** [comment]
@cob16 and myself bumped into a similar issue today. We fixed it with this in the config file:

```yaml
plugins:
  validate-links:
    repository: false
```

We found this option in the [remark-validate-links plugin documentation](https://unifiedjs.com/explore/package/remark-validate-links/#configuration)
